<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Umbraco.Community.VersionIndicator</PackageId>
    <Description>A community package that displays the Umbraco version in the backoffice.</Description>
    <Authors>erikjanwestendorp</Authors>
    <PackageTags>umbraco;version;indicator;backoffice</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbraco.Community.VersionIndicator.Assets\Umbraco.Community.VersionIndicator.Assets.csproj" />
  </ItemGroup>

</Project>
