<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>17.0.0-beta1</Version>
		<PackageId>Umbraco.Community.VersionIndicator</PackageId>
		<Product>Umbraco.Community.VersionIndicator</Product>
		<Title>Umbraco.Community.VersionIndicator</Title>
		<Description>A community package that displays the application version in the Umbraco backoffice.</Description>
		<Authors>Erik-Jan Westendorp</Authors>
		<PackageTags>umbraco plugin package version</PackageTags>
		<PackageProjectUrl>https://github.com/erikjanwestendorp/Umbraco.Community.VersionIndicator</PackageProjectUrl>
		<RepositoryUrl>https://github.com/erikjanwestendorp/Umbraco.Community.VersionIndicator</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Api.Management" />
		<PackageReference Include="Umbraco.Cms.Core" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Umbraco.Community.VersionIndicator.Assets\Umbraco.Community.VersionIndicator.Assets.csproj" />
	</ItemGroup>

</Project>
