<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>App_Plugins/VersionIndicator</StaticWebAssetBasePath>
	</PropertyGroup>

	<PropertyGroup>
		<Version>17.0.0-beta1</Version>
		<PackageId>Umbraco.Community.VersionIndicator.Assets</PackageId>
		<Product>Umbraco.Community.VersionIndicator.Assets</Product>
		<Title>Umbraco.Community.VersionIndicator.Assets</Title>
		<Description>Contains the static assets needed to run Umbraco.Community.VersionIndicator</Description>
		<Authors>Erik-Jan Westendorp</Authors>
		<PackageTags>umbraco plugin package version</PackageTags>
		<PackageProjectUrl>https://github.com/erikjanwestendorp/Umbraco.Community.VersionIndicator</PackageProjectUrl>
		<RepositoryUrl>https://github.com/erikjanwestendorp/Umbraco.Community.VersionIndicator</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>
	
</Project>
