name: Publish NuGet Packages

on:
  push:
    tags:
      - '*' 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore VersionIndicator
        run: dotnet restore ./src/Umbraco.Community.VersionIndicator/Umbraco.Community.VersionIndicator.csproj
      
      - name: Restore VersionIndicator.Assets
        run: dotnet restore ./src/Umbraco.Community.VersionIndicator.Assets/Umbraco.Community.VersionIndicator.Assets.csproj

      - name: Build VersionIndicator
        run: dotnet build ./src/Umbraco.Community.VersionIndicator/Umbraco.Community.VersionIndicator.csproj --configuration Release --no-restore

      - name: Build VersionIndicator.Assets
        run: dotnet build ./src/Umbraco.Community.VersionIndicator.Assets/Umbraco.Community.VersionIndicator.Assets.csproj --configuration Release --no-restore

      - name: Pack VersionIndicator
        run: dotnet pack ./src/Umbraco.Community.VersionIndicator/Umbraco.Community.VersionIndicator.csproj --configuration Release --no-build --output ./nupkg

      - name: Pack VersionIndicator.Assets
        run: dotnet pack ./src/Umbraco.Community.VersionIndicator.Assets/Umbraco.Community.VersionIndicator.Assets.csproj --configuration Release --no-build --output ./nupkg
      
      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push all .nupkg files to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate
